default_stages:
 - commit
 - merge-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
        stages:
          - commit
      - id: mixed-line-ending
        name: fix line ending
        stages:
          - commit
        args:
          - --fix=lf
      - id: mixed-line-ending
        name: check line ending
        stages:
          - merge-commit
        args:
          - --fix=no
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
      - id: add-trailing-comma
        stages:
          - commit
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        stages:
          - commit
        args:
          - --diff
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: fix import order
        stages:
          - commit
        args:
          - --line-length=120
          - --multi-line=9
          - --project=pjrpc
      - id: isort
        name: check import order
        stages:
          - merge-commit
        args:
          - --check-only
          - --line-length=120
          - --multi-line=9
          - --project=pjrpc
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        stages:
          - commit
        name: mypy
        pass_filenames: false
        args: ["--package", "pjrpc"]
